# Generated by Django 3.2.4 on 2021-06-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desenvolvedor', models.CharField(choices=[('Marcos', 'Marcos Allysson'), ('Douglas', 'Douglas Shibata'), ('Andre', 'Andre Luiz')], max_length=50, verbose_name='Desenvolvedor')),
                ('tecnologia', models.CharField(choices=[('PY', 'Python'), ('SQL', 'SQL'), ('SH', 'Bash')], max_length=50, verbose_name='Tecnologia')),
                ('comando', models.CharField(max_length=100, verbose_name='Comando')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descricao')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
        ),
    ]
