# Generated by Django 3.2.4 on 2021-06-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comandomodel_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandomodel',
            name='desenvolvedor',
            field=models.CharField(choices=[('Marcos', 'Marcos Allysson'), ('Douglas', 'Douglas Shibata')], max_length=50, verbose_name='Desenvolvedor'),
        ),
    ]
