# Generated by Django 3.2.4 on 2021-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comandomodel_desenvolvedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandomodel',
            options={'ordering': ['-criado']},
        ),
        migrations.AlterField(
            model_name='comandomodel',
            name='comando',
            field=models.CharField(max_length=255, verbose_name='Comando'),
        ),
        migrations.AlterField(
            model_name='comandomodel',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='comandomodel',
            name='tecnologia',
            field=models.CharField(choices=[('PY', 'Python'), ('SQL', 'SQL'), ('SH', 'Bash'), ('GIT', 'Git'), ('DJANGO', 'Django'), ('RASA', 'Rasa'), ('SCRIPT', 'Script'), ('DOCKER', 'Docker')], max_length=50, verbose_name='Tecnologia'),
        ),
    ]
